# Version: '2.1.2'
env:
  docker_tag: flyingduckio/duckdefender:latest
 
# This is a basic workflow to help you get started with GitHub Actions 
name: DuckDefender  
# Triggers the workflow on push events but only for the all the critical branches
on: 
  push:
    branches: [ "master", "main", "release", "develop" ]    
  
# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set environment variable
        env:
          USER_INPUT: ${{ github.event.inputs.user_input }}
        run: echo "$USER_INPUT"
 
      - name: Run DuckDefender
        run: |
          docker run -e GITHUB_REPOSITORY_OWNER="${{github.repository_owner}}" \
            -e EXIT_ON_ERROR=false \
            -e GITHUB_REPOSITORY_OWNER_ID="${{github.repository_owner_id}}" \
            -e GITHUB_REPOSITORY="${{github.repository}}" \
            -e GITHUB_REPOSITORY_ID="${{github.repository_id}}" \
            -e GITHUB_EVENT_NAME="${{github.event_name}}" \
            -e GITHUB_ACTOR="${{github.actor}}" \
            -e GITHUB_ACTOR_ID="${{github.actor_id}}" \
            -e FD_API_KEY="${{secrets.FD_API_KEY}}" \
            -e GITHUB_TOKEN="${{github.token}}" \
            -e GITHUB_HEAD_REF="${{github.head_ref}}" \
            -e GITHUB_BASE_REF="${{github.base_ref}}" \
            -e GITHUB_REF="${{github.ref}}" \
            -e GITHUB_SHA="${{github.sha}}" \
            -e WORKSPACE_PATH="/src" \
            -e LOG_LEVEL="debug" \
            -v "${{ github.workspace }}":/src \
            --entrypoint /bin/sh "${{env.docker_tag}}" -c "duckdefender code --all"
